const en = {
  welcome: "What would you like to build?",
  welcomeDescription: "Dcode can read this project, make changes, and run commands with you.",
  project: "Current project",
  suggestions: [
    { title: "Understand this codebase", prompt: "Summarize this project's structure and explain where to start." },
    { title: "Find a bug", prompt: "Inspect this project for a likely bug and propose a focused fix." },
    { title: "Plan a change", prompt: "Help me plan a small improvement to this project before editing files." },
  ],
  message: "Dcode",
  you: "You",
  thinking: "Thinking",
  working: "Working in your project",
  prompt: "Ask Dcode about this project…",
  hint: "Enter to send · Shift+Enter for a new line",
  viewChanges: "View changes",
  send: "Send",
  stop: "Stop",
  retry: "Retry",
  ready: "Ready",
  connecting: "Connecting",
  permission: "Permission needed",
  permissionDescription: "Review this operation before Dcode continues.",
  allowOnce: "Allow once",
  reject: "Reject",
  noModels: "No models available",
  activity: "Activity",
  activityCount: (count: number) => `${count} ${count === 1 ? "step" : "steps"}`,
  input: "Input",
  output: "Output",
  running: "Running",
  completed: "Done",
  failed: "Failed",
};

const zh: typeof en = {
  welcome: "今天想做点什么？",
  welcomeDescription: "Dcode 可以阅读当前项目、修改代码并运行命令。",
  project: "当前项目",
  suggestions: [
    { title: "了解项目", prompt: "概览这个项目的结构，并告诉我从哪里开始。" },
    { title: "排查问题", prompt: "检查这个项目中可能存在的问题，给出一个聚焦的修复建议。" },
    { title: "规划改动", prompt: "先帮我规划一项小改进，暂时不要修改文件。" },
  ],
  message: "Dcode",
  you: "你",
  thinking: "思考过程",
  working: "正在处理项目",
  prompt: "告诉 Dcode 你想完成什么…",
  hint: "Enter 发送 · Shift+Enter 换行",
  viewChanges: "查看改动",
  send: "发送",
  stop: "停止",
  retry: "重试",
  ready: "就绪",
  connecting: "连接中",
  permission: "需要确认",
  permissionDescription: "确认这项操作后，Dcode 会继续执行。",
  allowOnce: "允许一次",
  reject: "拒绝",
  noModels: "暂无可用模型",
  activity: "执行记录",
  activityCount: (count: number) => `${count} 项操作`,
  input: "输入",
  output: "输出",
  running: "进行中",
  completed: "已完成",
  failed: "失败",
};

export type DshCopy = typeof en;
export function getDshCopy(locale: string): DshCopy {
  return locale.startsWith("zh") ? zh : en;
}
